language: go
install:
  - go get -d -v ./...

script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o LiuliGo.cgi

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file: LiuliGo.cgi
  on:
    tags: true
    branch: master

